# Generated by Django 6.1 on 2026-09-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_orderitem_commission_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(choices=[(0.0, '0% (Exempt)'), (5.0, '5% (Essential/Apparel)'), (12.0, '12% (Processed Goods)'), (18.0, '18% (Standard/Electronics)'), (28.0, '28% (Luxury Goods)')], decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(default='851830', max_length=10),
        ),
    ]
