# Generated by Django 6.1 on 2026-09-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_gst_rate_alter_product_hsn_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('UPI', 'UPI / QR Code'), ('NET_BANKING', 'Internet Banking'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card')], default='COD', max_length=30),
        ),
    ]
