# Generated by Django 6.1 on 2026-09-10 01:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_categorypolicy_shippingratecard_order_awb_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='it_call_no',
            field=models.CharField(default='+91-1800-889-2026', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='live_tracking_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='support_reference_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_account_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_account_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_cheque_doc',
            field=models.FileField(blank=True, null=True, upload_to='seller_kyc/bank/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_ifsc_code',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='identity_proof_doc',
            field=models.FileField(blank=True, null=True, upload_to='seller_kyc/identity/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='is_orbiskart_mall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pan_doc',
            field=models.FileField(blank=True, null=True, upload_to='seller_kyc/pan/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='quality_score',
            field=models.DecimalField(decimal_places=1, default=Decimal('5.0'), max_digits=3),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='store_photo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_stores/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='warehouse_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='warehouse_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='SellerDeductionSlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slip_number', models.CharField(max_length=50, unique=True)),
                ('gross_order_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_collected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('courier_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_and_pg_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rto_risk_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('final_settlement_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_settled_to_bank', models.BooleanField(default=False)),
                ('settlement_reference_utr', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_slips', to='store.vendorprofile')),
            ],
        ),
    ]
