# Generated by Django 6.1 on 2026-09-14 07:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_it_call_no_order_live_tracking_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovtHSNMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(help_text='सरकार द्वारा निर्धारित 6 या 8 अंकों का HSN/SAC कोड', max_length=8, unique=True)),
                ('description', models.CharField(help_text='वस्तु या सेवा का आधिकारिक विवरण', max_length=255)),
                ('gst_rate', models.DecimalField(decimal_places=2, help_text='सरकारी GST दर (उदा: 5.00, 12.00, 18.00)', max_digits=5)),
                ('cess_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='अतिरिक्त उपकर (यदि लागू हो)', max_digits=5)),
                ('last_updated_gov', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Govt HSN Master',
                'verbose_name_plural': 'Govt HSN Masters',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='categorypolicy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='store.category'),
        ),
        migrations.AddField(
            model_name='shippingratecard',
            name='min_weight_grams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shippingratecard',
            name='zone',
            field=models.CharField(default='Regional', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('UPI', 'UPI / QR Code'), ('Razorpay-Prepaid', 'Razorpay Prepaid Online'), ('NET_BANKING', 'Internet Banking')], default='COD', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='shippingratecard',
            name='max_weight_grams',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='categorypolicy',
            name='hsn_master',
            field=models.ForeignKey(blank=True, help_text='सरकारी HSN मास्टर से ऑटोमैटिक GST', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.govthsnmaster'),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_record',
            field=models.ForeignKey(blank=True, help_text='सरकारी डेटाबेस से ऑटोमैटिक HSN', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.govthsnmaster'),
        ),
    ]
