# Generated by Django 6.1 on 2026-09-15 07:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_govthsnmaster_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shippingratecard',
            name='cod_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddField(
            model_name='shippingratecard',
            name='courier_partner',
            field=models.CharField(default='Delhivery', max_length=50),
        ),
        migrations.AddField(
            model_name='shippingratecard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shippingratecard',
            name='per_additional_500g',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='shippingratecard',
            name='forward_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('45.00'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='shippingratecard',
            name='zone',
            field=models.CharField(choices=[('Zone A', 'Zone A - Local (Within City)'), ('Zone B', 'Zone B - Regional (Within State)'), ('Zone C', 'Zone C - National Metro'), ('Zone D', 'Zone D - Rest of India'), ('Zone E', 'Zone E - Special (NE, J&K)')], default='Zone B', max_length=50),
        ),
        migrations.CreateModel(
            name='ImmutableMasterTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('service_type', models.CharField(choices=[('ECOMMERCE_ORDER', 'E-Commerce Order'), ('UTILITY_BILL', 'BBPS Utility Bill'), ('RECHARGE', 'Mobile/DTH Recharge'), ('GAS_BOOKING', 'LPG Gas Booking'), ('LOAN_REPAYMENT', 'Loan EMI Repayment'), ('SELLER_PAYOUT', 'Vendor Bank Settlement')], max_length=50)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gateway_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gst_on_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tcs_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('operator_ref', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(default='SUCCESS', max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='immutable_txs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderShippingReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_partner', models.CharField(default='Delhivery', max_length=50)),
                ('awb_number', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_weight_g', models.IntegerField(default=500)),
                ('actual_billed_weight_g', models.IntegerField(blank=True, null=True)),
                ('estimated_charge', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('actual_billed_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_discrepancy', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Estimated', 'अनुमानित (Estimated)'), ('In-Transit', 'मार्ग में (In-Transit)'), ('Delivered', 'डिलीवर (Delivered)'), ('Billed_Discrepancy', 'वजन अंतर (Discrepancy)'), ('Settled', 'बिल सेटल (Settled)')], default='Estimated', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_recon', to='store.order')),
            ],
        ),
    ]
