# Generated by Django 6.1 on 2026-09-15 08:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_shipping_pincode_shippingratecard_cod_charge_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='govthsnmaster',
            options={},
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='warehouse_lat',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='warehouse_lng',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='product_videos/'),
        ),
        migrations.AlterField(
            model_name='categorypolicy',
            name='hsn_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.govthsnmaster'),
        ),
        migrations.AlterField(
            model_name='govthsnmaster',
            name='cess_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='govthsnmaster',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='govthsnmaster',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='govthsnmaster',
            name='hsn_code',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hsn_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.govthsnmaster'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='store.product')),
            ],
        ),
    ]
