# Generated by Django 6.1 on 2026-09-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_govthsnmaster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='business_proof_doc',
            field=models.FileField(blank=True, null=True, upload_to='seller_kyc/business/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='city_district',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='id_proof_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='msme_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='penny_drop_utr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='penny_drop_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pincode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='state',
            field=models.CharField(default='Jharkhand', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='street_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
