# Generated by Django 6.1 on 2026-09-17 01:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_vendorprofile_business_proof_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_settled_to_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='settlement_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_utr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_weight_frozen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='package_height_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='package_length_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='package_photo',
            field=models.ImageField(blank=True, null=True, upload_to='weight_freeze_docs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_width_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6),
        ),
    ]
