# Generated by Django 6.1 on 2026-09-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_order_is_settled_to_vendor_order_settlement_due_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.RemoveField(
            model_name='immutablemastertransaction',
            name='gateway_fee',
        ),
        migrations.RemoveField(
            model_name='immutablemastertransaction',
            name='gst_on_commission',
        ),
        migrations.RemoveField(
            model_name='immutablemastertransaction',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='immutablemastertransaction',
            name='operator_ref',
        ),
        migrations.RemoveField(
            model_name='immutablemastertransaction',
            name='platform_commission',
        ),
        migrations.RemoveField(
            model_name='immutablemastertransaction',
            name='tcs_tax',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='gst_on_platform_fee',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='hsn_code',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='payment_gateway_fee',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='platform_commission',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_gst_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_gst_rate',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_and_return_fee',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='taxable_product_value',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_deductions',
        ),
        migrations.RemoveField(
            model_name='sellerdeductionslip',
            name='courier_charge',
        ),
        migrations.RemoveField(
            model_name='sellerdeductionslip',
            name='gross_order_amount',
        ),
        migrations.RemoveField(
            model_name='sellerdeductionslip',
            name='gst_collected',
        ),
        migrations.RemoveField(
            model_name='sellerdeductionslip',
            name='is_settled_to_bank',
        ),
        migrations.RemoveField(
            model_name='sellerdeductionslip',
            name='platform_and_pg_fee',
        ),
        migrations.RemoveField(
            model_name='sellerdeductionslip',
            name='rto_risk_deduction',
        ),
        migrations.RemoveField(
            model_name='sellerdeductionslip',
            name='settlement_reference_utr',
        ),
        migrations.AlterField(
            model_name='immutablemastertransaction',
            name='service_type',
            field=models.CharField(default='ECOMMERCE_ORDER', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
