# Generated by Django 6.1 on 2026-09-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_review_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='contact_number',
            new_name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='courier_contact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='it_call_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='live_tracking_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rider_contact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rider_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='support_reference_no',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='pincode',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_document',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/business/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='gstin_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='identity_proof',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/identity/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='ifsc_code',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='is_verified_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='msme_udyam_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='owner_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pin_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='shop_gps_photo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_docs/shop_gps/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='shop_name',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='COD', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Confirmed', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordershippingreconciliation',
            name='status',
            field=models.CharField(default='Estimated', max_length=30),
        ),
        migrations.AlterField(
            model_name='shippingratecard',
            name='zone',
            field=models.CharField(choices=[('Zone A', 'Zone A - Local'), ('Zone B', 'Zone B - Regional'), ('Zone C', 'Zone C - National Metro'), ('Zone D', 'Zone D - Rest of India'), ('Zone E', 'Zone E - Special')], default='Zone B', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
