# Generated by Django 6.1 on 2026-09-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_rename_contact_number_vendorprofile_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
